import { readFileSync, writeFileSync } from "fs";

const { version } = JSON.parse(readFileSync("package.json", "utf8"));
writeFileSync(
  "src/version.ts",
  `// Generated by scripts/genVersion.mjs — do not edit\nexport const SDK_VERSION = "${version}";\n`,
);
